### ISSUE TITLE
Error: Peer's Certificate issuer is not recognized.

### ISSUE THREAD

**Issue by jacksutherland** [craftcms/rackspace#2]
We have a Craft 3 site using this plugin, with all assets stored in a RackSpace CDN, and we'll occasionally get this error when uploading assets in the the CMS...

"Upload failed. The error message was: [curl] 60: Peer's Certificate issuer is not recognized. [url] https://identity.api.rackspacecloud.com/v2.0/tokens"

Rackspace was able to fix it the first time by "replacing the Guzzle certificate", and another time it happened I reimported a backup of the Craft database and it fixed it. But it keeps happening, and I have no idea why.

We also use Rackspace as a CDN for a bunch of Craft 2 sites and have never once had this error. It's always worked flawlessly. Do you know what this is? And can you help me sort it out?

**Comment by angrybrad** [comment]
Ultimately this comes down to this warning in the readme:

> Rackspace is no longer maintaining their PHP OpenCloud SDK, so you should probably find a different asset storage provider and not use this plugin.

This plugin uses `thephpleague/flysystem-rackspace`, which uses `rackspace/php-opencloud`, which uses an old/abandoned version of `guzzle/guzzle`.

https://github.com/thephpleague/flysystem-rackspace/issues/23

You might be able to fix it by replacing the cacert.pem file that's bundled with that Guzzle version, but that's just kicking the can down to the road, IMO: 

https://community.rackspace.com/products/f/dedicated-hybrid-hosting-forum/8674/rackspace-public-cloud-php-opencloud-sdk-errors-due-to-outdated-certificate-authority-list

**Comment by jacksutherland** [comment]
Is the Craft 2 Rackspace integration implemented differently than this plugin? Because we have about 5 Craft 2 sites using Rackspace file storage, and none of them have an issue.  Also, is there an alternative plugin available? Because not using Rackspace isn't really an option for us.

**Comment by angrybrad** [comment]
> Is the Craft 2 Rackspace integration implemented differently than this plugin?

Yes.

> Also, is there an alternative plugin available?

I'm not aware of one.

Did you try the `cacert.pem` fix?

**Comment by jacksutherland** [comment]
Yes. I forwarded that article to Rackspace before reaching out to you. It helped initially, but then the error came back. I'm not sure exactly what triggers it, but they just keep pointing to the library using a hardcoded old set of Certificate Authorities.

If I'm understanding correctly, it sounds like there's not really a permanent fix, and we just need to change our stack. I'm just looking for alternatives to avoid having to make a Rackspace vs Craft 3 decision.

**Comment by angrybrad** [comment]
> It helped initially, but then the error came back.

My guess is that the "fixed" `cacert.pem` file got overwritten during an update and the old one was put back in place. You'll want to take that into account when updating.
