### ISSUE TITLE
Plugin error with Craft version 3.0.13.2

### ISSUE THREAD

**Issue by jacksutherland** [craftcms/rackspace#3]
I just installed the plugin on a new Craft instance (version 3.0.13.2), and when I try to refresh the container drop down I get an error "An unknown error occurred". I'm using the same username and api key that works on multiple other Craft 2 and Craft 3 sites. The only difference from what I can tell is this instance is a newer version. Can you help me take a look?

The following is recorded in the web.log (I replaced username and apikey info) ...

2018-11-08 08:09:19 [-][1][-][info][yii\db\Command::execute] UPDATE `sessions` SET `dateUpdated`='2018-11-08 16:09:19' WHERE (`userId`='1') AND (`uid`='1f7b2273-7754-4e97-9b76-c7307654c653')
2018-11-08 08:09:19 [-][1][-][profile begin][yii\db\Command::execute] UPDATE `sessions` SET `dateUpdated`='2018-11-08 16:09:19' WHERE (`userId`='1') AND (`uid`='1f7b2273-7754-4e97-9b76-c7307654c653')
2018-11-08 08:09:19 [-][1][-][profile end][yii\db\Command::execute] UPDATE `sessions` SET `dateUpdated`='2018-11-08 16:09:19' WHERE (`userId`='1') AND (`uid`='1f7b2273-7754-4e97-9b76-c7307654c653')
2018-11-08 08:09:19 [-][1][-][trace][craft\web\Application::_processActionRequest] Route requested: 'rackspace'
2018-11-08 08:09:19 [-][1][-][trace][yii\base\Controller::runAction] Route to run: rackspace/default/load-container-data
2018-11-08 08:09:19 [-][1][-][trace][yii\base\InlineAction::runWithParams] Running action: craft\rackspace\controllers\DefaultController::actionLoadContainerData()
2018-11-08 08:09:20 [-][1][-][error][Guzzle\Http\Exception\CurlException] Guzzle\Http\Exception\CurlException: [curl] 60: SSL certificate problem: unable to get local issuer certificate [url] https://identity.api.rackspacecloud.com/v2.0/tokens in /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
Stack trace:
#0 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#5 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#6 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#7 /Users/jack/Overground/projects/polydeck-com/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#8 /Users/jack/Overground/projects/polydeck-com/vendor/rackspace/php-opencloud/lib/OpenCloud/Identity/Service.php(181): Guzzle\Http\Message\Request->send()
#9 /Users/jack/Overground/projects/polydeck-com/vendor/rackspace/php-opencloud/lib/OpenCloud/OpenStack.php(391): OpenCloud\Identity\Service->generateToken('{"auth":{"RAX-K...')
#10 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/rackspace/src/Volume.php(286): OpenCloud\OpenStack->authenticate()
#11 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/rackspace/src/Volume.php(129): craft\rackspace\Volume::client('username', 'apikey')
#12 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/rackspace/src/controllers/DefaultController.php(44): craft\rackspace\Volume::loadContainerList('username', 'apikey', 'IAD')
#13 [internal function]: craft\rackspace\controllers\DefaultController->actionLoadContainerData()
#14 /Users/jack/Overground/projects/polydeck-com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /Users/jack/Overground/projects/polydeck-com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('', Array)
#17 /Users/jack/Overground/projects/polydeck-com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('', Array)
#18 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('rackspace', Array)
#19 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('rackspace', Array)
#20 /Users/jack/Overground/projects/polydeck-com/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /Users/jack/Overground/projects/polydeck-com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /Users/jack/Overground/projects/polydeck-com/web/index.php(21): yii\base\Application->run()
#23 {main}
2018-11-08 08:09:19 [-][1][-][info][application] $_GET = [
    'p' => 'admin/actions/rackspace'
]

$_POST = [
    'username' => 'username'
    'apiKey' => '••••••••••••••••••••••••••••••••'
    'region' => 'IAD'
]

$_FILES = []

$_COOKIE = [
    '_ga' => 'GA1.1.586966177.1536270996'
    'vv_visitor_id' => 'wAaUBxgsxpCnASr6MIkB8z4MZvaAEgO'
    '__utmz' => '111872281.1537900323.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
    'kmL6444' => '1|0|Campaign not provided|AdGroup not provided|Raw Query not available|unk|Referrer information not available|Raw Query not available'
    'ffb833d38de9560f706220b7aa296766commerce_cookie' => '40b299d98113b8babceeb16582ab6862497df777s:96:\"77857688d6c954f997a4ba72a0c02b843f06f391czozMjoiZGNkYTgzOTI5N2FjZmEyYmNlYWYwY2IzMWE0Y2IxNTEiOw==\";'
    'd567a704d4fdb04fe52e165d8164d1facommerce_cookie' => 'ac6c0f2e54ec8b9dfda47f7795ed8c2bf437a894s:96:\"1d5b5ba36e5293f059bd1a2666e414e1d32c6200czozMjoiNDViN2FiZWFjMjJlNjQzODdjNGMyMjk5ZDc4ODYzMjQiOw==\";'
    'd567a704d4fdb04fe52e165d8164d1fausername' => '707d92126533e289b08cbea616f95042186b9e5as:64:\"89af5872dfe30e331ae29dbb0baaac483eece95cczoxMDoiT3Zlcmdyb3VuZCI7\";'
    '1bb2ab7a29e022f5a35c8c0cf539a17cusername' => '83bbc039efee8fb9cb9d0b8bd73e4d6fccaaaec7s:64:\"e37f3d40f1bdf7a3596fdc6823d0bb386b2e3949czoxMDoib3Zlcmdyb3VuZCI7\";'
    'ffb833d38de9560f706220b7aa296766username' => '3afe25272567bcd6ce06b0639aefcb401804e30ds:64:\"df7559d33c9cf0d5d27d019bc41270e564835310czoxMDoib3Zlcmdyb3VuZCI7\";'
    '__utma' => '111872281.586966177.1536270996.1538774248.1539098503.5'
    'kmE6444' => '1:0|17813.0|17809.0|17800.0|17799.'
    'countryRedirect' => '*'
    '1031b8c41dfff97a311a7ac99863bdc5_username' => 'df20e7b8f1d86d727809e1c30c6e91f34bbec251d9a4b79cd13c6f3c96a79c10a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:10:\"overground\";}'
    '1deb5fef1ea8406664799ebd464a89feusername' => '80209ec74c5cd527ffc41e09ab9d7515aadfb4ccs:68:\"8bf56353b98c8ab77031768a1e4bd4867264f5c8czoxMToiamFja3N1dGhlcmwiOw==\";'
    '43efff0b14499d42286cce7b40dde491username' => '85086e222accb06db3c09c8e79f98a794ba57d12s:68:\"5b5ef00eb1261c6d171b88f8d1704ac8d9d2dea0czoxMjoiVHJhaWxibGF6ZXJzIjs=\";'
    'driftt_aid' => '8dbeb26a-f9dc-491b-8511-ee4c316a3346'
    'calltrk_referrer' => 'direct'
    'calltrk_landing' => 'http://localhost/lp/account-based-marketing'
    '__adroll_fpc' => '6d9a6b901a790757b6498d7823e270d5'
    'DFTT_END_USER_PREV_BOOTSTRAPPED' => 'true'
    'exp_last_visit' => '1539098521'
    'kmE12156' => '1:0|17834.'
    'kmL12156' => '1|0|Campaign not provided|AdGroup not provided|Raw Query not available|unk|Referrer information not available|Raw Query not available'
    'exp_last_activity' => '1540929791'
    '_mkto_trk' => 'id:176-ORB-036&token:_mch-localhost-1536270995217-86360'
    '__ar_v4' => '3Y67QKZJXZCVRN4AU4BDAG:20181009:282|GKB7JUIY6ZFNXMQOOVAFMP:20181009:282|MT4BSD7WJ5HODCMXUGZ4VC:20181009:282|4XDE7EXSHZE25CBYNLSFJY:20181010:13|AZVQ6K3225ABFJT4G3V27P:20181010:13|YVSGP55VSJHJNCF3PUACGP:20181010:13|4JOJAZ4XGJHPHG43IJP2ZC:20181029:94|ACYVUTEFNNCQ3MWQ7DXM5A:20181029:94|WMVEGQHKWJDFBITPJTABRP:20181029:94'
    'SQLiteManager_currentLangue' => '2'
    'CraftSessionId' => 'a72646bec89c3a06c709d85e8626471e'
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => 'a23e0fefc45b15baa8918aa6905d7932850c147b8d130225437e049fd7384d8ba:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:285:\"[\"1\",\"[\\\"q5tAJuvTJHWP3Nnw3O5VxBVHiTVRbeqvMK0BbmkBZLp17kU98XHEa9QqGy6E88y7ky68pFLvHsFIU8ADP8LQaPBnmaqiVMhmWVLK\\\",\\\"1f7b2273-7754-4e97-9b76-c7307654c653\\\",\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36\\\"]\",3600]\";}'
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
]

**Comment by angrybrad** [comment]
> [curl] 60: SSL certificate problem: unable to get local issuer certificate [url] 

This feels like the same issue as https://github.com/craftcms/rackspace/issues/2

**Comment by jacksutherland** [comment]
Yes, unfortunately it seems like a recurring issue that is impossible to fix permanently. #2 was addressed on our RS server, for that site. However I'm now getting this error locally on brand new instances of Craft.

**Comment by jacksutherland** [comment]
Yes, except I get it locally now. I just replaced the cacert.pem on my local and it seems to work now. It just seems strange that this is something that has to continually be done, and can't be addressed. Rackspace Cloud has always worked great for us otherwise.
